image: node:latest

stages:
  # - build
  - test
  - lint
  - deploy

# build:
#   stage: build
#   script:
#     - echo "Do the build"
#     # - npm ci
#     # - npm run build

lint:
  stage: test
  script:
    # We use --no-package-lock to prevent npm from installing *everything* in package.json
    # FIXME: Add eslint
    - npm install --no-package-lock --no-save stylelint@11.1.1 stylelint-scss@3.13.0 stylelint-config-standard@19.0.0 stylelint-order@3.1.1
    - npm run lint

test-electron:
  stage: test
  image: cypress/base:10
  interruptible: true
  before_script:
    - npm ci
    - npm install --no-package-lock --no-save wait-on@3.2.0 cypress@3.6.1
  script:
    - npx wait-on http://localhost:1234
    - npm run start & npm run test

test-chrome:
  stage: test
  image: cypress/browsers:chrome67
  interruptible: true
  before_script:
    - ./scripts/install-chrome.sh
    - npm ci
    - npm install --no-package-lock --no-save wait-on@3.2.0 cypress@3.6.1
  script:
    - npm run start &
    - npx wait-on http://localhost:1234
    - npm run test --browser chrome
  artifacts:
    when: on_failure
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 10 days
