image: node:13.1.0-alpine3.10

stages:
  - prepare
  - build
  - test
  - deploy


cache:
  paths:
    - .npm/
    - node_modules/
  policy: pull



# PREPARE STAGE
# Only install deps if package.json or package-lock.json changed
Install dependencies:
  stage: prepare
  script:
    - npm ci --cache .npm --prefer-offline
  cache:
    paths:
      - .npm/
      - node_modules/
    policy: push
  # rules:
  #   - changes:
  #     - package.json
  #     - package-lock.json


# BUILD STAGE
Build:
  stage: build
  script:
    - npm run lint && npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week


# TEST STAGE
.test:
  stage: test
  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 1 week


Chrome and Firefox:
  extends: .test
  image: cypress/browsers:node12.13.0-chrome80-ff74
  script:
    - npm run test:chrome
    - npm run test:firefox


Edge:
  extends: .test
  image: cypress/base:13.1.0
  tags:
    - windows
  script:
    - npm run test:edge


# DEPLOY STAGE
# Deploy:
#   stage: deploy
#   only:
#     - master
#     - test
#   before_script:
#     - npm i -g firebase-tools
#   script:
#     - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
