image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

# this job installs NPM dependencies and Cypress
install:
  image: cypress/base:10
  stage: build

  script:
    - npm ci
    # show where the Cypress test runner binaries are cached
    - $(npm bin)/cypress cache path
    # show all installed versions of Cypress binary
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify

stages:
  - build
  - test
  - lint
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build

test-electron:
  stage: test
  image: cypress/base:10
  before_script:
    - npm install --no-package-lock --no-save wait-on@3.2.0 cypress@3.6.1
    - npm ci
  script:
    - npm ci
    - npm run test

test-chrome:
  stage: test
  image: cypress/browsers:chrome67
  before_script:
    - ./scripts/install-chrome.sh
    - npm install --no-package-lock --no-save wait-on@3.2.0 cypress@3.6.1
    - npm ci
  script:
    - npx wait-on http://localhost:1234
    - npm run test --browser chrome
  artifacts:
    when: on_failure
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 10 days


lint-scss:
  stage: test
  script:
    - npm ci
    - npm run sass-lint
