image: node:latest

stages:
  - build
  - test
  - lint
  - deploy

build:
  stage: build
  script:
    - echo "Do the build"
    # - npm ci
    # - npm run build

lint-scss:
  stage: test
  script:
    - npm ci
    - npm run sass-lint

test-electron:
  stage: test
  image: cypress/base:10
  interruptible: true
  before_script:
    - npm install --no-package-lock --no-save wait-on@3.2.0 cypress@3.6.1
    - npm ci
  script:
    - npx wait-on http://localhost:1234
    - npm run test

test-chrome:
  stage: test
  image: cypress/browsers:chrome67
  interruptible: true
  before_script:
    - ./scripts/install-chrome.sh
    - npm install --no-package-lock --no-save wait-on@3.2.0 cypress@3.6.1
    - npm ci
  script:
    - npx wait-on http://localhost:1234
    - npm run test --browser chrome
  artifacts:
    when: on_failure
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 10 days
