image: node:13.1.0-alpine3.10

stages:
  - prepare
  - build
  - lint
  - test
  - deploy

# Workaround for https://gitlab.com/gitlab-org/gitlab/issues/30631
no_needs:
  interruptible: true
  stage: prepare
  cache:
    key: noNeeds
    paths: []
  dependencies: []
  image: alpine:latest
  only:
    - merge_requests
    - master
  variables:
    GIT_STRATEGY: none
  script:
    - echo "This build is a workaround for 'https://gitlab.com/gitlab-org/gitlab/issues/30631

build:
  stage: build
  needs: [no_needs]
  script:
    - npm ci
    - npm run build
  artifacts:
    when: always
    paths:
      - dist

lint:
  stage: lint
  needs: [no_needs]
  script:
    # We use --no-package-lock to prevent npm from installing *everything* in package.json
    - npm install --no-package-lock --no-save stylelint@11.1.1 stylelint-scss@3.13.0 stylelint-config-standard@19.0.0 stylelint-order@3.1.1
    - npm install --no-package-lock --no-save eslint@6.6.0 eslint-plugin-cypress@2.7.0
    - npm run lint

.e2e:
  stage: test
  image: cypress/base:12.13.0
  needs: [build]
  interruptible: true
  before_script:
    - npm ci
    - npm install --no-package-lock --no-save wait-on@3.2.0 cypress@3.6.1
    - npm run start &
    - npx wait-on http://localhost:3000
  artifacts:
    when: always
    paths:
      - dist
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 10 days

test-chrome:
  extends: .e2e
  image: cypress/browsers:node12.13.0-chrome78-ff70
  script:
    - npm run test --browser chrome

test-electron:
  extends: .e2e
  script:
    - npm run test

deploy:
  stage: deploy
  needs: [lint, test-chrome, test-electron]
  script:
    - npm ci
    - npm i -g firebase-tools
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
