workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'



variables:
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/cypress
  POT_CI_ENABLE_DEPLOY_PROD_JOB: 'true'
  POT_CI_ENABLE_FLIP_PROD_JOB: 'true'


include:
  - project: 'potato/own-things/quality/gitlab-ci-includes'
    file: 'deploy/firebase.deploy.gitlab-ci.yml'
    ref: '10-firebase-deploy-inc'


image: node:14.15.4-alpine3.12


cache: &fe_deps
  key:
    files:
      - package.json
      - package-lock.json
    prefix: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/
    - cache/cypress/
  untracked: true
  policy: pull


stages:
  - Prep
  - Build
  - Test
  - Deploy


# PREP STAGE
# Install deps if package.json or package-lock.json changed or commit pushed to default branch
Install deps:
  stage: Prep
  cache:
    <<: *fe_deps
    policy: push
  interruptible: true
  script:
    - npm ci


# BUILD STAGE
Build:
  stage: Build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  interruptible: true
  script:
    - npm run build

Lint:
  stage: Build
  script:
    - npm run lint


# TEST STAGE
.test:
  stage: Test
  image: cypress/browsers:node14.15.0-chrome86-ff82
  interruptible: true
  artifacts:
    when: on_failure
    paths:
      - cypress/screenshots
    expire_in: 1 week
  script:
    - npm run test:ci:prep
    - npm run test:ci:$BROWSER

Chrome:
  extends: .test
  variables:
    BROWSER: 'chrome'

Firefox:
  extends: .test
  variables:
    BROWSER: 'firefox'

# Edge not working atm need to investigate why
# Edge:
#   extends: .test
#   image: cypress/browsers:node14.10.1-edge88
#   allow_failure: true
#   variables:
#     BROWSER: 'edge'


# DEPLOY STAGE
.deploy_job:
  cache: {}
  needs: [Build]
